name: Meshery Playground - Reset
on:
   workflow_dispatch:
   schedule:
     - cron:  '0 0 * * *'  # Run the job every day at midnight

jobs:
   reset:
     name: Cluster Reset
     if: github.repository == 'meshery/meshery'
     runs-on: ubuntu-latest 
     steps:
      - uses: azure/setup-kubectl@v3
      - name: Extract kubeconfig
        run: mkdir ~/.kube; touch ~/.kube/config ;echo "${{ secrets.PLAYGROUND_CONFIG }}" | base64 --decode > ~/.kube/config
      - name: Delete namespaces except the ones which are whitelisted in the if statement
        run: |
         for ns in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}");
         do
         if [[ "$ns" != "kube-system" && "$ns" != "default" && "$ns" != "monitoring" && "$ns" != "kube-flannel" && "$ns" != "kube-node-lease" && "$ns" != "kube-public" && "$ns" != "meshery" && "$ns" != "metallb-system" && "$ns" != "projectcontour" ]];then
           echo "Deleting namespace $ns"
           kubectl delete ns "$ns"
          fi
         done

